### ISSUE TITLE
Consider a different license?

### ISSUE THREAD

**Issue by photex** [Firstyear/concread#5]
Howdy!

This looks like interesting and useful work. But the LGPL would be very hard to comply with using the standard rust tooling. Is there another license that might suit you and make it easier for this crate to be more widely used?

**Comment by photex** [comment]
LGPL was built with the C universe in mind. If you statically link with an LGPL library then users of this library have to provide either source or object files on request in order to relink that product when needed.
That's pretty difficult to comply with when it comes to rust and cargo. But I also can see the argument that the overwhelming majority of products being created with Rust are open source already.
The Rust community at large probably has a lot of thoughts on the matter. It might be worth starting a discussion in the user forums. 
I'm under the impression most crates are using MPL or MIT.

**Comment by Firstyear** [comment]
A lot of my work has historically been C - and I did overlook the rust static linking behaviour. For now, I'll look at MPL and MIT, and I will update these shortly (probably in the next hour). Thanks for bringing this up!

**Comment by Firstyear** [comment]
Closing as resolved: 0.1.1 now is MPL and published. Thanks for your help!

**Comment by photex** [comment]
Awesome! Happy to be of service and really happy to see this crate. :D
