### ISSUE TITLE
Make cowcell T Send + 'static

### ISSUE THREAD

**Issue by Firstyear** [Firstyear/concread#6]
https://github.com/Firstyear/crossbeam-concread/pull/1#issuecomment-371348212

This issue describes a situation in the original EbrCell code. Investigate if it applies to the CowCell as well. (Arc may be protecting us here ...)

**Comment by Firstyear** [comment]
@vtec234 Hey there, a long time ago you helped with a review of an EbrCell for me about Send + 'static. I think the same thing applies here with the Arc version, but I'd like to be sure with some more experienced eyes. The construct uses a Mutex<Arc<T>>, which I would assume at least resolves the "Send" component of the issue. The reference lifetime issue I'm not so sure about, but reading the example you provided last time I suspect that it *is* still a problem even with this implementation. What do you think?

**Comment by Firstyear** [comment]
https://github.com/Firstyear/concread/blob/master/src/cowcell.rs is the code in question.

**Comment by Firstyear** [comment]
I've just run the unsound test, and it passes, so thinking more about this, I believe that this is fine as if there was an issue it would affect the core Arc<T> type, and given that correctly behaves on drop when going out of scope, so does CowCell. As a result, we don't need the send + static.

**Comment by Vtec234** [comment]
Hey, sorry for the delay. The linked code contains no `unsafe` blocks, so it must be safe regardless of what you do (barring Rust compiler bugs). The problem in `EbrCell` was due to the use of `defer`, which is not used here.
